modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="bxtreme"
version="1.0.0"
displayName="BXtreme Performance"
description='''
Extreme FPS optimization for low-end Android devices.
Maximum performance, zero compromises.
'''
authors="Bludos"

[[dependencies.bxtreme]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.bxtreme]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"